
'''
From a dataset of triplanes (presumably generated by our diffusion model), use the EG3D decoder to
create the corresponding directory of 3D shapes.

No rendering required -- we are testing 3D/4D (first just 3D) capabilities of our model.
'''

